# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  rootDir: 'hearthstone-viewer'
  buildDir: '$(rootDir)/build'
  copyDir: '$(rootDir)/copy'
  archiveDir: '$(buildDir)/archive'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    mkdir -p -- $(rootDir)
    mkdir -p -- $(buildDir)
    mkdir -p -- $(copyDir)
    mkdir -p -- $(Build.ArtifactStagingDirectory)
  displayName: 'Makes sure directories exist'

- script: |
    cd $(rootDir)
    npm install
    npm run build
    cd ..
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(buildDir)'
    includeRootFolder: false
    archiveType: 'tar'
    tarCompression: 'gz'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build_$(Build.BuildId).tar.gz'
    replaceExistingArchive: true
    verbose: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/build_$(Build.BuildId).tar.gz'
    ArtifactName: 'drop'
    publishLocation: 'Container'
# (Build.ArtifactStagingDirectory)