# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  rootDir: 'hearthstone-viewer'
  buildDir: '$(rootDir)/build'
  archiveDir: '$(buildDir)/archive'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    mkdir -p -- $(rootDir)
    mkdir -p -- $(buildDir)
    mkdir -p -- $(Build.ArtifactStagingDirectory)
  displayName: 'Makes sure directories exist'

- script: |
    cd $(rootDir)
    npm install
    npm run build
    cd ..
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(buildDir)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(archiveDir)/build_$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(archiveDir)/build_$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'